// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oop_s2_2_mvc_71739.Data;

#nullable disable

namespace oop_s2_2_mvc_71739.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326093834_InitialFoodSafety")]
    partial class InitialFoodSafety
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("oop_s2_2_mvc_71739.Models.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("FollowUps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 4,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 2,
                            ClosedDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 6,
                            Status = "Closed"
                        },
                        new
                        {
                            Id = 3,
                            DueDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 9,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 4,
                            ClosedDate = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 11,
                            Status = "Closed"
                        },
                        new
                        {
                            Id = 5,
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 15,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 6,
                            DueDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 17,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 7,
                            DueDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 20,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 8,
                            ClosedDate = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 25,
                            Status = "Closed"
                        },
                        new
                        {
                            Id = 9,
                            DueDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 9,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 10,
                            DueDate = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 11,
                            Status = "Open"
                        });
                });

            modelBuilder.Entity("oop_s2_2_mvc_71739.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PremisesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PremisesId");

                    b.ToTable("Inspections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InspectionDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good hygiene practices.",
                            Outcome = "Pass",
                            PremisesId = 1,
                            Score = 92
                        },
                        new
                        {
                            Id = 2,
                            InspectionDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Minor documentation gaps.",
                            Outcome = "Pass",
                            PremisesId = 2,
                            Score = 78
                        },
                        new
                        {
                            Id = 3,
                            InspectionDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Clean storage areas.",
                            Outcome = "Pass",
                            PremisesId = 3,
                            Score = 88
                        },
                        new
                        {
                            Id = 4,
                            InspectionDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Temperature logs missing.",
                            Outcome = "Fail",
                            PremisesId = 4,
                            Score = 62
                        },
                        new
                        {
                            Id = 5,
                            InspectionDate = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Sanitizer levels acceptable.",
                            Outcome = "Pass",
                            PremisesId = 5,
                            Score = 75
                        },
                        new
                        {
                            Id = 6,
                            InspectionDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cross-contamination risk.",
                            Outcome = "Fail",
                            PremisesId = 6,
                            Score = 54
                        },
                        new
                        {
                            Id = 7,
                            InspectionDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Improved from last visit.",
                            Outcome = "Pass",
                            PremisesId = 7,
                            Score = 81
                        },
                        new
                        {
                            Id = 8,
                            InspectionDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Excellent record keeping.",
                            Outcome = "Pass",
                            PremisesId = 8,
                            Score = 95
                        },
                        new
                        {
                            Id = 9,
                            InspectionDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Pest control issues.",
                            Outcome = "Fail",
                            PremisesId = 9,
                            Score = 68
                        },
                        new
                        {
                            Id = 10,
                            InspectionDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Staff training updated.",
                            Outcome = "Pass",
                            PremisesId = 10,
                            Score = 83
                        },
                        new
                        {
                            Id = 11,
                            InspectionDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Food storage violations.",
                            Outcome = "Fail",
                            PremisesId = 11,
                            Score = 59
                        },
                        new
                        {
                            Id = 12,
                            InspectionDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Well maintained kitchen.",
                            Outcome = "Pass",
                            PremisesId = 12,
                            Score = 90
                        },
                        new
                        {
                            Id = 13,
                            InspectionDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "No major issues.",
                            Outcome = "Pass",
                            PremisesId = 1,
                            Score = 86
                        },
                        new
                        {
                            Id = 14,
                            InspectionDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Needs label updates.",
                            Outcome = "Pass",
                            PremisesId = 2,
                            Score = 73
                        },
                        new
                        {
                            Id = 15,
                            InspectionDate = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cleaning schedule inconsistent.",
                            Outcome = "Fail",
                            PremisesId = 3,
                            Score = 64
                        },
                        new
                        {
                            Id = 16,
                            InspectionDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Improved compliance.",
                            Outcome = "Pass",
                            PremisesId = 4,
                            Score = 70
                        },
                        new
                        {
                            Id = 17,
                            InspectionDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Handwashing sink issues.",
                            Outcome = "Fail",
                            PremisesId = 5,
                            Score = 58
                        },
                        new
                        {
                            Id = 18,
                            InspectionDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Ventilation cleaned.",
                            Outcome = "Pass",
                            PremisesId = 6,
                            Score = 79
                        },
                        new
                        {
                            Id = 19,
                            InspectionDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "No critical findings.",
                            Outcome = "Pass",
                            PremisesId = 7,
                            Score = 82
                        },
                        new
                        {
                            Id = 20,
                            InspectionDate = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Expired ingredients found.",
                            Outcome = "Fail",
                            PremisesId = 8,
                            Score = 61
                        },
                        new
                        {
                            Id = 21,
                            InspectionDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good improvement.",
                            Outcome = "Pass",
                            PremisesId = 9,
                            Score = 88
                        },
                        new
                        {
                            Id = 22,
                            InspectionDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Strong controls.",
                            Outcome = "Pass",
                            PremisesId = 10,
                            Score = 91
                        },
                        new
                        {
                            Id = 23,
                            InspectionDate = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Minor repairs needed.",
                            Outcome = "Pass",
                            PremisesId = 11,
                            Score = 76
                        },
                        new
                        {
                            Id = 24,
                            InspectionDate = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Routine visit.",
                            Outcome = "Pass",
                            PremisesId = 12,
                            Score = 84
                        },
                        new
                        {
                            Id = 25,
                            InspectionDate = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cooling unit maintenance.",
                            Outcome = "Fail",
                            PremisesId = 6,
                            Score = 66
                        });
                });

            modelBuilder.Entity("oop_s2_2_mvc_71739.Models.Premises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Premises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Maple St",
                            Name = "Sunrise Deli",
                            RiskRating = "Low",
                            Town = "Riverton"
                        },
                        new
                        {
                            Id = 2,
                            Address = "5 Dock Rd",
                            Name = "Harbor Grill",
                            RiskRating = "Medium",
                            Town = "Bayview"
                        },
                        new
                        {
                            Id = 3,
                            Address = "44 Oak Ave",
                            Name = "Oakfield Bakery",
                            RiskRating = "Low",
                            Town = "Oakfield"
                        },
                        new
                        {
                            Id = 4,
                            Address = "18 River Ln",
                            Name = "Riverton Sushi",
                            RiskRating = "High",
                            Town = "Riverton"
                        },
                        new
                        {
                            Id = 5,
                            Address = "201 Coast Blvd",
                            Name = "Bayview Tacos",
                            RiskRating = "Medium",
                            Town = "Bayview"
                        },
                        new
                        {
                            Id = 6,
                            Address = "77 Pine Rd",
                            Name = "Oakfield Bistro",
                            RiskRating = "High",
                            Town = "Oakfield"
                        },
                        new
                        {
                            Id = 7,
                            Address = "3 Market Sq",
                            Name = "Riverton Cafe",
                            RiskRating = "Medium",
                            Town = "Riverton"
                        },
                        new
                        {
                            Id = 8,
                            Address = "9 Harbor St",
                            Name = "Bayview Pizza",
                            RiskRating = "Low",
                            Town = "Bayview"
                        },
                        new
                        {
                            Id = 9,
                            Address = "122 Main St",
                            Name = "Oakfield Diner",
                            RiskRating = "Medium",
                            Town = "Oakfield"
                        },
                        new
                        {
                            Id = 10,
                            Address = "65 Canal Way",
                            Name = "Riverbank Noodles",
                            RiskRating = "High",
                            Town = "Riverton"
                        },
                        new
                        {
                            Id = 11,
                            Address = "400 Ocean Dr",
                            Name = "Seaside Snacks",
                            RiskRating = "High",
                            Town = "Bayview"
                        },
                        new
                        {
                            Id = 12,
                            Address = "14 Pine St",
                            Name = "Pine Street Eatery",
                            RiskRating = "Low",
                            Town = "Oakfield"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("oop_s2_2_mvc_71739.Models.FollowUp", b =>
                {
                    b.HasOne("oop_s2_2_mvc_71739.Models.Inspection", "Inspection")
                        .WithMany("FollowUps")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("oop_s2_2_mvc_71739.Models.Inspection", b =>
                {
                    b.HasOne("oop_s2_2_mvc_71739.Models.Premises", "Premises")
                        .WithMany("Inspections")
                        .HasForeignKey("PremisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premises");
                });

            modelBuilder.Entity("oop_s2_2_mvc_71739.Models.Inspection", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("oop_s2_2_mvc_71739.Models.Premises", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
